ImageResizer/Models/Image.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageResizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    using System.Drawing;

    public partial class Image
    {
        public int ImageId { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        //public Image ImageDetails { get; set; }

        public int Width { get; set; }
        public int Height { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    }
}

ImageResizer/Controllers/ImageController.cs
using ImagerLib.Modules.Resizer;
using ImagerLib.Modules.Converter;
using ImageResizer.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImagerLib;

namespace ImageResizer.Controllers
{
    public class ImageController : Controller
    {
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Image imageModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
            string extension = Path.GetExtension(imageModel.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssff") + extension;
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"),fileName);
            imageModel.ImageFile.SaveAs(fileName);
            using (DbModelsss db = new DbModelsss())
            {
                db.Images.Add(imageModel);
                db.SaveChanges();
            }
            ModelState.Clear();
            return View();
        }

        [HttpGet]
        public ActionResult View(int id)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }

            return View(imageModel);
        }

        public ActionResult Resize(int id)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }

            return View(imageModel);
        }

        public ActionResult ResizeOptions(int id)
        {
            Image imageModel = new Image();


            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }
            
            string fileName = Path.GetFileName(imageModel.ImagePath);

            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            
            System.Drawing.Image sourceImage = System.Drawing.Image.FromFile(fileName);
            

            return View(imageModel);
        }
        
        public ActionResult Resizing(Image model)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == 0).FirstOrDefault();
            }


            string fileName = Path.GetFileName(imageModel.ImagePath);
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            string destName = Path.GetFileName(imageModel.ImagePath);
            destName = Path.Combine(Server.MapPath("~/Image/Resized/"), destName);

            Imager imager = new Imager();


            try
            { 
            imager.Resize(fileName, destName,ResizeType.KeepAspect,model.Width,model.Height);
            }

            catch(Exception ex)
            {
                return View("Error", ex);
            }
            return RedirectToAction("View/0");
        }

        public ActionResult Crop(int id)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }

            string fileName = Path.GetFileName(imageModel.ImagePath);

            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            System.Drawing.Image sourceImage = System.Drawing.Image.FromFile(fileName);
            
            return View(imageModel);
        }

        public ActionResult Cropping(Image model)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == 0).FirstOrDefault();
            }

            string fileName = Path.GetFileName(imageModel.ImagePath);
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            string destName = Path.GetFileName(imageModel.ImagePath);
            destName = Path.Combine(Server.MapPath("~/Image/Cropped/"), destName);

            Imager imager = new Imager();


            try
            {
                imager.Resize(fileName, destName, ResizeType.Crop, model.Width, model.Height, model.X, model.Y);
            }

            catch (Exception ex)
            {
                return View("Error", ex);
            }

            return RedirectToAction("View/0");
        }


        public ActionResult Skew(int id)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }

            string fileName = Path.GetFileName(imageModel.ImagePath);

            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            System.Drawing.Image sourceImage = System.Drawing.Image.FromFile(fileName);
            
            return View(imageModel);
        }

        public ActionResult Skewing(Image model)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == 0).FirstOrDefault();
            }

            string fileName = Path.GetFileName(imageModel.ImagePath);
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            string destName = Path.GetFileName(imageModel.ImagePath);
            destName = Path.Combine(Server.MapPath("~/Image/Skewed/"), destName);

            Imager imager = new Imager();
            try
            {
                imager.Resize(fileName, destName, ResizeType.Skew, model.Width, model.Height);
            }

            catch (Exception ex)
            {
                return View("Error", ex);
            }


            return RedirectToAction("View/0");

        }

        

        public ActionResult Convert(int id)
        {
            Image imageModel = new Image();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }

            return View(imageModel);
        }

        public ActionResult ToGif(int id)
        {
            Image imageModel = new Image();
            Imager imager = new Imager();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }
            string fileName = Path.GetFileName(imageModel.ImagePath);
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            string destName = Path.GetFileNameWithoutExtension(imageModel.ImagePath);
            destName = Path.Combine(Server.MapPath("~/Image/ToGif/"), destName );
            destName += ".gif";
            
            try
            {
                imager.Convert(fileName, destName, ConvertType.Gif);
            }

            catch (Exception ex)
            {
                return View("Error", ex);
            }



            return RedirectToAction("View/0");
        }

        public ActionResult ToPng(int id)
        {
            Image imageModel = new Image();
            Imager imager = new Imager();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }
            string fileName = Path.GetFileName(imageModel.ImagePath);
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            string destName = Path.GetFileNameWithoutExtension(imageModel.ImagePath);
            destName = Path.Combine(Server.MapPath("~/Image/ToPng/"), destName);
            destName += ".png";
            
            try
            {
                imager.Convert(fileName, destName, ConvertType.Png);
            }

            catch (Exception ex)
            {
                return View("Error", ex);
            }


            return RedirectToAction("View/0");

        }


        public ActionResult ToJpg(int id)
        {
            Image imageModel = new Image();
            Imager imager = new Imager();

            using (DbModelsss db = new DbModelsss())
            {
                imageModel = db.Images.Where(x => x.ImageId == id).FirstOrDefault();
            }
            string fileName = Path.GetFileName(imageModel.ImagePath);
            imageModel.ImagePath = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);

            string destName = Path.GetFileNameWithoutExtension(imageModel.ImagePath);
            destName = Path.Combine(Server.MapPath("~/Image/ToJpg/"), destName);
            destName += ".jpg";


            

            try
            {
                imager.Convert(fileName, destName, ConvertType.Jpg);
            }

            catch (Exception ex)
            {
                return View("Error", ex);
            }


            return RedirectToAction("View/0");
        }

    }
}

ImageResizer/Views/Image/Add.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>


@using (Html.BeginForm("Add","Image",FormMethod.Post,new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add picture" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ImageResizer/Views/Image/Convert.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "Convert";
}

<h2>Convert</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" />
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("To Gif", "ToGif", new { id = Model.ImageId }) |
    @Html.ActionLink("To Png", "ToPng", new { id = Model.ImageId }) |
    @Html.ActionLink("To Jpg", "ToJpg", new { id = Model.ImageId})
</p>

<b>
    @Html.ActionLink("Go back", "View/0")
</b>

ImageResizer/Views/Image/Crop.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "Crop";
}

<h2>Choose crop options</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" />
        </dd>

    </dl>
</div>


@using (Ajax.BeginForm("Cropping", "Image",new AjaxOptions { UpdateTargetId = "divInterestDeatils" }))
{
    <fieldset>
        <legend>Enter new parameters</legend>
        <div id="divInterestDeatils"></div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Width)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Width)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Height)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.X)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.X)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Y)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Y)
        </div>
        
        <p>
            <input type="submit" value="Upload" />
        </p>

        <b>
            @Html.ActionLink("Go back", "Resize/0")
        </b>

    </fieldset>
}

ImageResizer/Views/Image/Resize.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "Resize";
}

<h2>Choose resize options</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" />
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Resize", "ResizeOptions", new { id = Model.ImageId }) |
    @Html.ActionLink("Crop", "Crop", new { id = Model.ImageId }) |
    @Html.ActionLink("Skew", "Skew",new { id = Model.ImageId }) |

    <b>
        @Html.ActionLink("Go back", "View/0")
</b>
</p>

ImageResizer/Views/Image/ResizeOptions.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "Resize Options";
}

<h2>Choose resize options</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" />
        </dd>

    </dl>
</div>

<p>Enter new width and height</p>

@using (Ajax.BeginForm("Resizing", "Image",new AjaxOptions { UpdateTargetId = "divInterestDeatils" }))
{

    <fieldset>
        <legend>Enter new parameters</legend>
        <div id="divInterestDeatils"></div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Width)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Width)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Height)
        </div>
        <p>
            <input type="submit" value="Upload" />
        </p>

        <b>
            @Html.ActionLink("Go back", "Resize/0")
        </b>
    </fieldset>
}  

ImageResizer/Views/Image/Skew.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "Skew Options";
}

<h2>Choose resize options</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" />
        </dd>

    </dl>
</div>

<p>Enter new width and height</p>

@using (Ajax.BeginForm("Skewing", "Image", new AjaxOptions { UpdateTargetId = "divInterestDeatils" }))
{

    <fieldset>
        <legend>Enter new parameters</legend>
        <div id="divInterestDeatils"></div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Width)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Width)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Height)
        </div>
        <p>
            <input type="submit" value="Upload" />
        </p>
        <b>
            @Html.ActionLink("Go back", "Resize/0")
        </b>

    </fieldset>
}

ImageResizer/Views/Image/View.cshtml
@model ImageResizer.Models.Image

@{
    ViewBag.Title = "View";
}


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImagePath)" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Resize", "Resize", new { id = Model.ImageId }) |
    @Html.ActionLink("Convert", "Convert", new { id = Model.ImageId }) |
    @Html.ActionLink("Do Absolutely Nothing","Add")
</p>